Update links.yml
PawseySC/pawseysc.github.io pull request #11
Opened 2020-10-27 01:31 UTC by ratkinson0405

Update the links to the 'Using Supercomputers - Parts 1 & 2'.

2020-10-27 05:41 UTC, marcodelapierre requested changes
Hi Rob, just a couple of comments:

1- add "git: https://github.com/PawseySC/Introductory-Supercomputing" to both trainings, as they both use these github materials

2- right now the youtube "vid" links point to the same video, this needs fixing. I just checked on youtube and noticed that right now the order of the videos in that playlist is wrong and needs fixing, too, so these links will need to change again. Maybe fix the links with the current youtube config, and I will keep you in the loop on the youtube fix.

2020-10-28 06:44 UTC, ratkinson0405 commented
Hi Marco, I've added the github materials links. I have also updated the vid links, but they appeared to link to the same videos. I may need to clarify the vid links with you.

2020-10-29 03:23 UTC, marcodelapierre approved these changes

2020-10-29 03:24 UTC, marcodelapierre commented
thanks Rob, I have just done a further edit to the youtube links, so that watching starts from the beginning rather than from a custom time

2020-10-29 03:24 UTC, merged